### ISSUE TITLE
Unable to launch game via original config window (AkibaUU_Config.exe)

### ISSUE THREAD

**Issue by RadarNyan** [spideyfusion/akiba#1]
After tuning configuration and hit play (プレイ) the program crashes with following message:

```
---------------------------
AkibaInterceptor
---------------------------
System.ComponentModel.Win32Exception (0x80004005): Unknown error (0x80041002)

   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)

   at System.Diagnostics.Process.Start()

   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)

   at Akiba.Core.Utilities.LaunchSteamGame(UInt32 applicationId)

   at Akiba.Program.LaunchConfigurationUtility()

   at Akiba.Program.Main(String[] args)
---------------------------
OK   
---------------------------
```

I can't seem to be able to change the game language setting with the patch installed.

**Comment by spideyfusion** [comment]
Thanks for the report @RadarNyan. What version of Windows are you running (and what architecture)?

* Are you able to launch the game directly from Steam with AkibaInterceptor installed?
* Are you able to launch the game using Steam's browser protocol?
    * Press the **Windows + R** keys and run `steam://run/333980`

**Comment by RadarNyan** [comment]
**Running the game itself is fine** with the patch installed. I can play the game and the patch seems to be working for me. It's just I can't run the game via the original config window, therefore no way to change game language once the patch has been installed (hitting cancel button doesn't seem to affect in-game language, the config window changes language though).

( I'm running Windows 7 x64 SP1 with latest .net version and all Windows updates to date. )

**Comment by spideyfusion** [comment]
Have you tried the second bullet point from my previous comment? It'll help me narrow down the issue you're having.

**Comment by RadarNyan** [comment]
My bad, Steam protocol indeed didn't work and I have a pretty good idea why. It works once I got that handled. Sorry about the false report.

**Comment by spideyfusion** [comment]
Not a problem. Glad I could help. Maybe we could add a more friendly error message for this case so affected users can know where to look in order to solve their problem. :)
