### ISSUE TITLE
not functioning

### ISSUE THREAD

**Issue by kuroyukikageya** [spideyfusion/akiba#3]
i followed every procedure and still cant get 60fps even though the frame rate is set to 60. is it because this program is too old?

**Comment by spideyfusion** [comment]
The tool is still supported and I just tested it on a Windows 10 installation and it works fine. I'm going to need more details in order do help you:

* What are your system specifications?
* What version of Windows are you using?
* With the game still running, can you see `AkibaInterceptor` under `Processes` when you open the Task Manager?
* Can you post the contents of your `configuration.yaml` file?

**Comment by kuroyukikageya** [comment]
Acer predator helios 300 (gtx 1060 6gb, i7-7700HQ cpu)
Windows 10
Yes AkibaInterceptor is running when im playin the game
other than fps the motion blur is quite high even though it is zero in the game setting. might be fps problem
![capture](https://user-images.githubusercontent.com/43206625/45438885-f2fbf080-b6ea-11e8-9473-baa64c3ad8d6.PNG)

**Comment by spideyfusion** [comment]
Can you turn on the `In-game FPS counter` and tell me what FPS you're getting on the main menu? It's under **Steam -> Settings -> In-Game**.

**Comment by kuroyukikageya** [comment]
sorry for the late reply. here is the fps in main menu and in game. 
main menu fps is around 30fps, in game fps is 10-15fps
sorry for the fps indicator being not clear
![main menu](https://user-images.githubusercontent.com/43206625/45557524-5f542c80-b870-11e8-926e-46206b0906cd.png)
![in game](https://user-images.githubusercontent.com/43206625/45557528-62e7b380-b870-11e8-9780-8e77159552a8.png)

**Comment by spideyfusion** [comment]
Here are my two suggestions for you to try:

* Your laptop has a dedicated and an integrated GPU. Try forcing the system to use the NVIDIA GPU for AKIBA'S TRIP:
    * Go into the NVIDIA Control Panel (**Start Menu -> Control Panel -> Hardware and Sound -> NVIDIA Control Panel**).
    * On the left select the "**3D Settings -> Manage 3D Settings**" menu item.
    * Click on the "**Program Settings**" tab and select AKIBA'S TRIP from the list (if it's not on the list, click the "**Add**" button to add it).
    * Make sure that for AKIBA'S TRIP the "**Preferred graphics processor**" setting is set to "**High performance NVIDIA processor**".
    * Don't forget to **Apply** the settings.
* Update the NVIDIA drivers to the [latest](https://www.nvidia.com/Download/driverResults.aspx/137729/en-us) version.

**Comment by kuroyukikageya** [comment]
Thank you very much. Everything works perfectly and i get constant 60fps. Thanks for your help mate.
