### ISSUE TITLE
Doesn't work on GOG version

### ISSUE THREAD

**Issue by 1chiTheKiller** [spideyfusion/akiba#8]
It tries to open the Steam version exclusively.  I bought this game on GOG, therefore it can't be used unless I knew how to change it.  Considering I don't know how to code, it makes it a bit difficult to figure out how to fix this issue.

**Comment by spideyfusion** [comment]
@1chiTheKiller Thanks for the report. It appears they also added an option to control game FPS and resolutions beyond 1920x1080 through the configuration UI itself.

I'm working on updating AkibaInterceptor to support the new game update as we speak. The update will also include support for GOG (both Galaxy and DRM-free versions).

**Comment by spideyfusion** [comment]
Support for GOG has been added in [v1.4.0](https://github.com/spideyfusion/akiba/releases/tag/v1.4.0).

**Comment by 1chiTheKiller** [comment]
THANK YOU THANK YOU THANK YOU!!!! :D

I just got this on GOG and really wanted to play it but I found it REALLY bizarre that it was exclusively locked to 30FPS with no simple way to unlock the framerate even to 60.  Seriously, thanks for hopping on this one.  Very much appreciated. ^_^
